### ISSUE TITLE
Cannot display the correct localization

### ISSUE THREAD

**Issue by christchan** [andresilvagomez/Localize#21]
Hi, I have a problem using this localization framework.

Here is the step I have done

1. install localize using cocoapods
2. import Localize in AppDelegate.swift and put below code inside "application" function
`let localize = Localize.shared`
`localize.update(provider: .json)`
`localize.update(fileName: "lang")`
`localize.update(defaultLanguage: "en")`
`print(localize.language())`
`print(localize.availableLanguages())`
3. then, I created "lang-en.json" and put it inside my working folder
4. I add `print("hello.world".localize())` somewhere in the viewController
5. I tried to run the program
6. the result which is shown in the console is
`en`
`[]`
`hello.world`

Am I missing something? or they cannot find my "lang-en.json" file?

Thank you

**Comment by andresilvagomez** [comment]
@christchan sorry I'm back to the project, do you have yet this issue?
