### ISSUE TITLE
Localization not working with Localizable.strings file

### ISSUE THREAD

**Issue by thang2410199** [andresilvagomez/Localize#26]
I used `Localizable.strings` according to Apple guideline, and it works with 
`NSLocalizedString("key", comment: "")`

Now I try to use Localize and `"key".localized` and it display `key`, not the proper value

**Comment by andresilvagomez** [comment]
@thang2410199 hey I hope all is ok,
Could you share me the environment please.
iOS Version, Xcode version, are you using CocoaPods or Carthage?, etc

**Comment by thang2410199** [comment]
I work with iOS 11.3, latest Xcode 9.3 (9E145) and cocoapod.

**Comment by andresilvagomez** [comment]
@thang2410199 thanks for your report I found the issue and I fix i.

Its ready in CocoaPods

thanks for all, have a good day.

 -> Localize (2.0.3)

Updating spec repo `master`

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  Localize (2.0.3) successfully published
 📅  May 15th, 08:58
 🌎  https://cocoapods.org/pods/Localize
 👍  Tell your friends!
--------------------------------------------------------------------------------

**Comment by andresilvagomez** [comment]
@thang2410199 remember 

you can use this if your string file is named Strings.string
```
print("hello.world".localized)
```

If you have a different file name, in your app delegate

```
import Localize
.....
Localize.update(fileName: "yourname")
```

and use the first code part.

Thanks for all !!

**Comment by andresilvagomez** [comment]
Please let me know if it works for you
