### ISSUE TITLE
Keep the string that had localize key

### ISSUE THREAD

**Issue by hungcao2112** [andresilvagomez/Localize#30]
Base on your example, what if I want to keep the string "app.label" without remove its key. For example, I want to localize "app.label" in the first viewcontroller but I don't want to localize "app.label" in the second viewcontroller. Any solutions ?

**Comment by andresilvagomez** [comment]
@hungcao2112 Hello, right maybe this is an error because the Localize will localize the component, maybe a good solutions is create a property to prevent localize some UI elements, @hungcao2112 thanks for it, I'll include in the next version.

**Comment by andresilvagomez** [comment]
@hungcao2112 this is currently implemented
