### ISSUE TITLE
Localize with parameter not work

### ISSUE THREAD

**Issue by purepure** [andresilvagomez/Localize#32]
Hi!
I am trying to localize a key like this:
"This_is_key" = "You have % apples";
But it always fallback to base language. (in my case, I localize for Vietnamese). But the key without parameters still working in Vietnamese.

I tried so many ways but it still not working.

Please check

**Comment by andresilvagomez** [comment]
@purepure Hii I Hope you are ok!!

Are you using JSON or Strings, could you attach me your configuration please

**Comment by purepure** [comment]
I am using .strings file.
FYI:
``` Localize.update(fileName: "Localization")
        //Localize.update(defaultLanguage: "en-US")
        Localize.update(defaultLanguage: "vi")
        Localize.update(language: "vi-Việt Nam!")```

Here is the code printing localization text

```print("current: \(Localize.currentLanguage)") -> vi-VN
        print("Page page total".localize(values: "\(page)", "\(photos.count - (1 - offset))"))
        print("Not recommend".localized)
        print("manga_count Mangas".localize(value: "123"))```

output:
```current: vi-VN
Page 1 / 14 
Không khuyến khích
123 Mangas```


Strings file:

```"Page page total" = "Trang % / %";``` -> but it always print out English version instead of this

**Comment by pvn-anh-pham** [comment]
Hi! 
any update? do you need any further information of this issue, plz dont hesitate to ask me. I will try my best to support.

**Comment by purepure** [comment]
It seem this repos was abandoned. But I still hope someone look at this issue and fix it, It would be great because the features of this lib is awesome except it wouldn't work as designed

**Comment by ggrana** [comment]
I believe that the PR #36 will fix this.

**Comment by purepure** [comment]
Thank, I will check and reply soon 👍

**Comment by andresilvagomez** [comment]
@purepure Awesome, thanks a lot to @ggrana
