### ISSUE TITLE
Not localizing automatically

### ISSUE THREAD

**Issue by LinusGeffarth** [andresilvagomez/Localize#38]
First off, thanks for this awesome library. I love how simple, yet flexible, it is!
Keep up the good work!

---

I've setup localization for English and German: `lang-en.json`, `lang-de.json`.
It works perfectly when manually setting the language in code by doing `localize.update(language: "de")`. 
However, it does not automatically set the language when changing my device's language.

Am I missing something?

---

### Update:

I figured I could manually set the language to the device's language by passing...

    Locale.preferredLanguages.first?.components(separatedBy: "-").first.lowercased ?? "en"

...as language code.  
Is this the way it's supposed to be?

**Comment by andresilvagomez** [comment]
@LinusGeffarth Good morning, thanks for your comments I really appreciate it

@LinusGeffarth could you send me your config lines, remember to use JSON provider you need create a method like to 

```swift
private func configLang() {
        // This need keep in the first line.
        Localize.update(provider: .json)
        Localize.update(fileName: "lang")
        Localize.update(language: "de")
    }
```

Let me know some news, I hope you have a good day.

**Comment by andresilvagomez** [comment]
@LinusGeffarth I'll check it, I'm not sure why it's happening

**Comment by andresilvagomez** [comment]
@LinusGeffarth I so sorry I was in a vacations mode, I checked it and works fine, I used this code

```swift
let locale = Locale.preferredLanguages.first?.components(separatedBy: "-").first?.lowercased() ?? "es"
Localize.shared.update(language: locale)
```

Let me know some news

**Comment by LinusGeffarth** [comment]
That's my code, ha.
Soo this is the default way to do it? It doesn't automatically do that?

**Comment by andresilvagomez** [comment]
@LinusGeffarth Yes It works automatically I tested all cases, I understood your question was related if that code works.

All UI Updated automatically but if you assigned some string in the code you need to attach this code to change.

```swift
NotificationCenter.default.addObserver(
    self,
    selector: #selector(localize),
    name: NSNotification.Name(localizeChangeNotification),
    object: nil
 )
```

```swift
@objc localize() {
    // And recall your strings here
}
```
