### ISSUE TITLE
Support for simplified and traditional  Chinese

### ISSUE THREAD

**Issue by przemokrk** [andresilvagomez/Localize#48]
# Issue

The library does not handle properly languages that are coded by iOS in three components. I have tried to include translation for both simplified and traditional Chinese. The language variable is set as follow:

- zh-Hans-US for simplified Chinese
- zh-Hant-US for the traditional Chinese

However, I cannot create json resource with the name zh-Hans-US / zh-Hant-US as last component encode the regional settings. In my case  it is US. I have tried  to name files: lang-zh-Hant.json  and lang-zh-Hans.json but it results in selecting default language as the library always fall back to the single component file name (lang-zh.json) which also cannot be found.

## Localize Environment

- **Localize version:**
- **Xcode version:**
- **Swift version:**
- **Platform(s) running Localize:**
- **macOS version running Xcode:**

## Localize Config

```swift
/// Please put here your config
```

## What did you do?

ℹ Please replace this with what you did.

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

ℹ Please replace this with of what happened instead.

**Comment by jeanmartin** [comment]
It works for me.
Make sure you included `Localize.update(provider: .json)` if you want to use JSON files.

I'm using `lang-zh-Hant-HK.json` and it works just fine.

**Comment by przemokrk** [comment]
Correct, it would work but the problem that I point here is that you have
to include as many json files as regions that your users may be located (HK
in your case).  In reality you may need several files to cover people
located in other part of the world who just selected simplified Chinese as
a language for the interface. Therefore, I would propose that the file name
should be lang-zh-Hant.json. (without HK at the end)

**Comment by 404NotFun** [comment]
The locale name should match ios `NSLocale.availableLocaleIdentifiers`.
I had encountered the same issue when I use `lang-zh-Hant-TW.json`.
I solved it by changing the file name to `lang-zh_Hant_TW.json`

**Comment by przemokrk** [comment]
Thanks! It is the same workaround that I made to resolve the problem.
