### ISSUE TITLE
Determine whether a localization exists for a key

### ISSUE THREAD

**Issue by LinusGeffarth** [andresilvagomez/Localize#50]
For error messages, I try to generically access the localized strings.

Example json:

```json
"errors": {
    "some_error": "Something went wrong!",
    "some_other_error": "We're not sure what's happening..."
}
```
From the API, I receive an error code and would like to do:

```swift
let errorCode = ... // from API response
let errorMessage = "errors.\(errorCode)".localized
```
Now, in case I forgot to add localization for an error code, or the backend added a new error code, before I was able to update the app, I'd like to do a fallback, when there's no localized string for this key.  
Currently, I compare the returned string to the key:

```swift
let key = "errors.\(errorCode)"
if key.localized != key {
    errorMessage = "There's an unknown error."
}
```
However, I'd much rather do something like this:

```swift
let key = "errors.\(errorCode)"
if Localize.shared.localizationExists(forKey: key) {
```
See a possible implementation for this below:

```swift
/// Determines whether a localized string exists for given key
///
/// - parameter key: localization key
/// - returns: boolean value determining whether a localized string exists for give key
public func localizationExists(forKey key: String) -> Bool {
    return key.localized != key
}
```

**Comment by andresilvagomez** [comment]
Sorry was my error 👎 I leave this project for a while, I'm implementing it right now
