### ISSUE TITLE
How to handle Localizable.strings file

### ISSUE THREAD

**Issue by ajay2c9** [andresilvagomez/Localize#51]
Hi,
This is not an issue according to this pod. I already used this pod in another iOS application. It is nice and very easy to understand and easy to implement.  
I have a situation here. I am working a project which already contains localization file for the two languages. The code is written is like this for the text. 
NSLocalizedString("Use_Thumb", comment: "")

Is there any possibility to use this pod to handle the Localizable.strings file. If possible. How to use it.

The project is updated to swift 4.2 version.

 please give suggestions.

![screen shot 2019-02-23 at 12 37 24 pm](https://user-images.githubusercontent.com/9112899/53283151-e08ce500-3767-11e9-959d-1577c45efbd3.png)

**Comment by andresilvagomez** [comment]
@ajay2c9 Sorry was my error 👎  I leave this project for a while
