### ISSUE TITLE
Please release 2.2.0 to CocoaPods

### ISSUE THREAD

**Issue by tladesignz** [andresilvagomez/Localize#52]
CocoaPods still shows 2.1.0 as latest:

https://cocoapods.org/pods/Localize

Please release 2.2.0 there! Thanks!

**Comment by andresilvagomez** [comment]
🎉  Congrats

 🚀  Localize (2.2.0) successfully published
 📅  April 3rd, 19:21
 🌎  https://cocoapods.org/pods/Localize
 👍  Tell your friends!

**Comment by tladesignz** [comment]
Thanks a ton!
